In [2]:
%pip install python-dotenv
%pip install pandas

Requirement already satisfied: python-dotenv in c:\users\hp\desktop\projects 2025\autoexpense\venv\lib\site-packages (1.0.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.1.3; however, version 25.0.1 is available.
You should consider upgrading via the 'c:\Users\hp\Desktop\PROJECTS 2025\AutoExpense\venv\Scripts\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: pandas in c:\users\hp\desktop\projects 2025\autoexpense\venv\lib\site-packages (2.2.3)Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.1.3; however, version 25.0.1 is available.
You should consider upgrading via the 'c:\Users\hp\Desktop\PROJECTS 2025\AutoExpense\venv\Scripts\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\desktop\projects 2025\autoexpense\venv\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\desktop\projects 2025\autoexpense\venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\desktop\projects 2025\autoexpense\venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\desktop\projects 2025\autoexpense\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\hp\desktop\projects 2025\autoexpense\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

**Data Loading/Importing Google Sheets**

In [3]:
##Loading the required variables from the .env file

from dotenv import load_dotenv
import os

# Load environment variables from a .env file
load_dotenv()

# Access the environment variables
sheet_id = os.getenv('SHEET_ID')

In [4]:
%pwd

'c:\\Users\\hp\\Desktop\\PROJECTS 2025\\AutoExpense\\Experiments'

In [5]:
%cd ..

c:\Users\hp\Desktop\PROJECTS 2025\AutoExpense

c:\Users\hp\Desktop\PROJECTS 2025\AutoExpense\venv\lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [6]:
import gspread
from google.oauth2.service_account import Credentials

# Define the scope
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]

# Add credentials to the account
creds = Credentials.from_service_account_file('credentials.json', scopes=scope)

# Authorize the clientsheet 
client = gspread.authorize(creds)

# Get the sheet by name
sheet = client.open_by_key(sheet_id).worksheet("master_test")

# Print the sheet data
data = sheet.get_all_records()
data

[{'Date': '21/06/2022',
  'Month': 'June',
  'Name of expense': 'Lotion',
  'Type of expense': 'Accessories',
  'Amount': 195,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '21/06/2022',
  'Month': 'June',
  'Name of expense': 'Smokies',
  'Type of expense': 'Thrills',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '22/06/2022',
  'Month': 'June',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '22/06/2022',
  'Month': 'June',
  'Name of expense': 'ID application fee',
  'Type of expense': 'Utilities',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '22/06/2022',
  'Month': 'June',
  'Name of expense': 'Eggs',
  'Type of expense': 'Food',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '22/06/2022',
  'Month': 'June',
  'Name of expense': 'Printing Fee',
  'Type of expense': 'Petty Cash',
  'Amount': 5,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '22/06/2022',
  'Month': 'June',
  'Name of expense': 'Toilet',
  'Type of expense': 'Petty Cash',
  'Amount': 10,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '22/06/2022',
  'Month': 'June',
  'Name of expense': 'KDF',
  'Type of expense': 'Thrills',
  'Amount': 20,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '22/06/2022',
  'Month': 'June',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 230,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '24/06/2022',
  'Month': 'June',
  'Name of expense': 'Suppository',
  'Type of expense': 'Medicine',
  'Amount': 180,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '24/06/2022',
  'Month': 'June',
  'Name of expense': 'Mandazi',
  'Type of expense': 'Food',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '24/06/2022',
  'Month': 'June',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '24/06/2022',
  'Month': 'June',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 270,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '24/06/2022',
  'Month': 'June',
  'Name of expense': 'Spotify',
  'Type of expense': 'Utilities',
  'Amount': 149,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '25/06/2022',
  'Month': 'June',
  'Name of expense': 'Buscopan',
  'Type of expense': 'Medicine',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '25/06/2022',
  'Month': 'June',
  'Name of expense': 'Mzish',
  'Type of expense': 'Entertainment',
  'Amount': 375,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '25/06/2022',
  'Month': 'June',
  'Name of expense': 'Cakes',
  'Type of expense': 'Thrills',
  'Amount': 90,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '25/06/2022',
  'Month': 'June',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 180,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '26/06/2022',
  'Month': 'June',
  'Name of expense': 'KFC',
  'Type of expense': 'Entertainment',
  'Amount': 449,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '26/06/2022',
  'Month': 'June',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 150,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '27/06/2022',
  'Month': 'June',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '27/06/2022',
  'Month': 'June',
  'Name of expense': 'Eggs',
  'Type of expense': 'Food',
  'Amount': 45,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '28/06/2022',
  'Month': 'June',
  'Name of expense': 'Mandazi',
  'Type of expense': 'Food',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '28/06/2022',
  'Month': 'June',
  'Name of expense': 'Smokies',
  'Type of expense': 'Thrills',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '28/06/2022',
  'Month': 'June',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 120,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '29/06/2022',
  'Month': 'June',
  'Name of expense': 'A Pair of shorts',
  'Type of expense': 'Clothes',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '29/06/2022',
  'Month': 'June',
  'Name of expense': 'Shawarma',
  'Type of expense': 'Thrills',
  'Amount': 250,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '30/06/2022',
  'Month': 'June',
  'Name of expense': 'Eggs',
  'Type of expense': 'Food',
  'Amount': 45,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '01/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '01/07/2022',
  'Month': 'July',
  'Name of expense': 'Tots',
  'Type of expense': 'Entertainment',
  'Amount': 3070,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '01/07/2022',
  'Month': 'July',
  'Name of expense': 'Fresh Chewing Gums',
  'Type of expense': 'Thrills',
  'Amount': 20,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '01/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 80,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '02/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '02/07/2022',
  'Month': 'July',
  'Name of expense': 'Mandazi',
  'Type of expense': 'Food',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '02/07/2022',
  'Month': 'July',
  'Name of expense': 'Smocha',
  'Type of expense': 'Thrills',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '02/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 250,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '03/07/2022',
  'Month': 'July',
  'Name of expense': 'Galitos Juice',
  'Type of expense': 'Thrills',
  'Amount': 195,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '03/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 180,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '07/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '07/07/2022',
  'Month': 'July',
  'Name of expense': 'Bluetooth Speaker',
  'Type of expense': 'Accessories',
  'Amount': 872,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '07/07/2022',
  'Month': 'July',
  'Name of expense': 'NHIF',
  'Type of expense': 'Utilities',
  'Amount': 500,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '08/07/2022',
  'Month': 'July',
  'Name of expense': 'Chips',
  'Type of expense': 'Thrills',
  'Amount': 270,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '10/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '10/07/2022',
  'Month': 'July',
  'Name of expense': 'Clothes',
  'Type of expense': 'Clothes',
  'Amount': 500,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '10/07/2022',
  'Month': 'July',
  'Name of expense': 'Shawarma',
  'Type of expense': 'Thrills',
  'Amount': 600,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '10/07/2022',
  'Month': 'July',
  'Name of expense': 'Uber',
  'Type of expense': 'Transport',
  'Amount': 560,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '13/07/2022',
  'Month': 'July',
  'Name of expense': 'Key Cutting',
  'Type of expense': 'Household Items',
  'Amount': 150,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '13/07/2022',
  'Month': 'July',
  'Name of expense': 'Chapati',
  'Type of expense': 'Thrills',
  'Amount': 20,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '13/07/2022',
  'Month': 'July',
  'Name of expense': 'Smokies',
  'Type of expense': 'Thrills',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '14/07/2022',
  'Month': 'July',
  'Name of expense': 'Toilet',
  'Type of expense': 'Petty Cash',
  'Amount': 10,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '14/07/2022',
  'Month': 'July',
  'Name of expense': 'Park Fees',
  'Type of expense': 'Entertainment',
  'Amount': 270,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '14/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 150,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '14/07/2022',
  'Month': 'July',
  'Name of expense': 'Chicken Inn',
  'Type of expense': 'Thrills',
  'Amount': 690,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '14/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 380,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '15/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '15/07/2022',
  'Month': 'July',
  'Name of expense': 'KFC',
  'Type of expense': 'Thrills',
  'Amount': 639,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '18/07/2022',
  'Month': 'July',
  'Name of expense': 'Wooven Bag',
  'Type of expense': 'Petty Cash',
  'Amount': 15,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '18/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '18/07/2022',
  'Month': 'July',
  'Name of expense': 'Haircut',
  'Type of expense': 'Accessories',
  'Amount': 150,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '18/07/2022',
  'Month': 'July',
  'Name of expense': 'Face Scrub',
  'Type of expense': 'Household Items',
  'Amount': 477,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '18/07/2022',
  'Month': 'July',
  'Name of expense': 'Salt',
  'Type of expense': 'Household Items',
  'Amount': 69,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '19/07/2022',
  'Month': 'July',
  'Name of expense': 'Toilet',
  'Type of expense': 'Petty Cash',
  'Amount': 10,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '19/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 300,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '19/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 360,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '20/07/2022',
  'Month': 'July',
  'Name of expense': 'Bitez',
  'Type of expense': 'Petty Cash',
  'Amount': 50,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '22/07/2022',
  'Month': 'July',
  'Name of expense': 'Toilet',
  'Type of expense': 'Petty Cash',
  'Amount': 10,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '22/07/2022',
  'Month': 'July',
  'Name of expense': 'Sweets',
  'Type of expense': 'Petty Cash',
  'Amount': 10,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '22/07/2022',
  'Month': 'July',
  'Name of expense': 'MJ',
  'Type of expense': 'Entertainment',
  'Amount': 250,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '22/07/2022',
  'Month': 'July',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '22/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 180,
  'Comments': '',
  'Year': 2022,
  'Day': 'Friday'},
 {'Date': '23/07/2022',
  'Month': 'July',
  'Name of expense': 'Gibs',
  'Type of expense': 'Entertainment',
  'Amount': 949,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '23/07/2022',
  'Month': 'July',
  'Name of expense': 'Sprite',
  'Type of expense': 'Entertainment',
  'Amount': 120,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '23/07/2022',
  'Month': 'July',
  'Name of expense': 'BlackIce',
  'Type of expense': 'Entertainment',
  'Amount': 149,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '23/07/2022',
  'Month': 'July',
  'Name of expense': 'Eggs',
  'Type of expense': 'Food',
  'Amount': 90,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '23/07/2022',
  'Month': 'July',
  'Name of expense': 'Smokies',
  'Type of expense': 'Thrills',
  'Amount': 35,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '23/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 70,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '24/07/2022',
  'Month': 'July',
  'Name of expense': 'KFC',
  'Type of expense': 'Thrills',
  'Amount': 639,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '26/07/2022',
  'Month': 'July',
  'Name of expense': 'Pilipili',
  'Type of expense': 'Food',
  'Amount': 5,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '26/07/2022',
  'Month': 'July',
  'Name of expense': 'Bread',
  'Type of expense': 'Food',
  'Amount': 60,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '26/07/2022',
  'Month': 'July',
  'Name of expense': 'Mandazi',
  'Type of expense': 'Thrills',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '27/07/2022',
  'Month': 'July',
  'Name of expense': 'Eggs',
  'Type of expense': 'Food',
  'Amount': 90,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '28/07/2022',
  'Month': 'July',
  'Name of expense': 'Printing Fee',
  'Type of expense': 'Petty Cash',
  'Amount': 262,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '28/07/2022',
  'Month': 'July',
  'Name of expense': 'Toilet',
  'Type of expense': 'Petty Cash',
  'Amount': 20,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '28/07/2022',
  'Month': 'July',
  'Name of expense': 'Galitos Chicken + Water',
  'Type of expense': 'Food',
  'Amount': 790,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '28/07/2022',
  'Month': 'July',
  'Name of expense': 'Soda',
  'Type of expense': 'Thrills',
  'Amount': 70,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '28/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 310,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '28/07/2022',
  'Month': 'July',
  'Name of expense': 'NSSF',
  'Type of expense': 'Utilities',
  'Amount': 25,
  'Comments': '',
  'Year': 2022,
  'Day': 'Thursday'},
 {'Date': '30/07/2022',
  'Month': 'July',
  'Name of expense': 'Bounty',
  'Type of expense': 'Thrills',
  'Amount': 130,
  'Comments': '',
  'Year': 2022,
  'Day': 'Saturday'},
 {'Date': '31/07/2022',
  'Month': 'July',
  'Name of expense': 'Cabbage',
  'Type of expense': 'Food',
  'Amount': 10,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '31/07/2022',
  'Month': 'July',
  'Name of expense': 'Water',
  'Type of expense': 'Food',
  'Amount': 80,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '31/07/2022',
  'Month': 'July',
  'Name of expense': 'Purple Chewing Gum',
  'Type of expense': 'Thrills',
  'Amount': 50,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '31/07/2022',
  'Month': 'July',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 150,
  'Comments': '',
  'Year': 2022,
  'Day': 'Sunday'},
 {'Date': '01/08/2022',
  'Month': 'August',
  'Name of expense': 'Printing Fee',
  'Type of expense': 'Petty Cash',
  'Amount': 30,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '01/08/2022',
  'Month': 'August',
  'Name of expense': 'Rings',
  'Type of expense': 'Clothes',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '01/08/2022',
  'Month': 'August',
  'Name of expense': 'Comb',
  'Type of expense': 'Accessories',
  'Amount': 95,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '01/08/2022',
  'Month': 'August',
  'Name of expense': 'Spray Bottle',
  'Type of expense': 'Accessories',
  'Amount': 140,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '01/08/2022',
  'Month': 'August',
  'Name of expense': 'NHIF application fee',
  'Type of expense': 'Utilities',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '01/08/2022',
  'Month': 'August',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '01/08/2022',
  'Month': 'August',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 160,
  'Comments': '',
  'Year': 2022,
  'Day': 'Monday'},
 {'Date': '02/08/2022',
  'Month': 'August',
  'Name of expense': 'Printing Fee',
  'Type of expense': 'Petty Cash',
  'Amount': 65,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '02/08/2022',
  'Month': 'August',
  'Name of expense': 'Credit',
  'Type of expense': 'Credit',
  'Amount': 100,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '02/08/2022',
  'Month': 'August',
  'Name of expense': 'Offering',
  'Type of expense': 'Goodwill',
  'Amount': 50,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '02/08/2022',
  'Month': 'August',
  'Name of expense': 'Candy',
  'Type of expense': 'Thrills',
  'Amount': 150,
  'Comments': '',
  'Year': 2022,
  'Day': 'Tuesday'},
 {'Date': '03/08/2022',
  'Month': 'August',
  'Name of expense': 'Food Handlers Cert',
  'Type of expense': 'Utilities',
  'Amount': 1000,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '03/08/2022',
  'Month': 'August',
  'Name of expense': 'Toilet',
  'Type of expense': 'Petty Cash',
  'Amount': 20,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '03/08/2022',
  'Month': 'August',
  'Name of expense': 'Goodwill',
  'Type of expense': 'Goodwill',
  'Amount': 120,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '03/08/2022',
  'Month': 'August',
  'Name of expense': 'Rings',
  'Type of expense': 'Clothes',
  'Amount': 200,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '03/08/2022',
  'Month': 'August',
  'Name of expense': 'Chicken Inn',
  'Type of expense': 'Entertainment',
  'Amount': 965,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '03/08/2022',
  'Month': 'August',
  'Name of expense': 'Smokies',
  'Type of expense': 'Thrills',
  'Amount': 70,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '03/08/2022',
  'Month': 'August',
  'Name of expense': 'Fare',
  'Type of expense': 'Transport',
  'Amount': 160,
  'Comments': '',
  'Year': 2022,
  'Day': 'Wednesday'},
 {'Date': '04/08/2022',
  'Month': 'August',
  'Name of expense': 'Scanning Fee',
  'Type of expense': 'Petty Cash',
  'Amount': 40,
  'Comments': '',

In [7]:
import pandas as pd

# Convert the data to a DataFrame
df = pd.DataFrame(data)
df.head()

,Date,Month,Name of expense,Type of expense,Amount,Comments,Year,Day
0,21/06/2022,June,Lotion,Accessories,195.0,,2022,Tuesday
1,21/06/2022,June,Smokies,Thrills,30.0,,2022,Tuesday
2,22/06/2022,June,Credit,Credit,100.0,,2022,Wednesday
3,22/06/2022,June,ID application fee,Utilities,100.0,,2022,Wednesday
4,22/06/2022,June,Eggs,Food,30.0,,2022,Wednesday

**Data Validation**

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3510 entries, 0 to 3509
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             3510 non-null   object
 1   Month            3510 non-null   object
 2   Name of expense  3510 non-null   object
 3   Type of expense  3510 non-null   object
 4   Amount           3510 non-null   float64
 5   Comments         3510 non-null   object
 6   Year             3510 non-null   int64
 7   Day              3510 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 219.5+ KB

In [9]:
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')
df.dtypes

Date               datetime64[ns]
Month                      object
Name of expense            object
Type of expense            object
Amount                    float64
Comments                   object
Year                        int64
Day                        object
dtype: object

In [12]:
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
df.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_21316\2096952888.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

,Date,Month,Name of expense,Type of expense,Amount,Comments,Year,Day
0,2022-06-21,June,Lotion,Accessories,195.0,,2022,Tuesday
1,2022-06-21,June,Smokies,Thrills,30.0,,2022,Tuesday
2,2022-06-22,June,Credit,Credit,100.0,,2022,Wednesday
3,2022-06-22,June,ID application fee,Utilities,100.0,,2022,Wednesday
4,2022-06-22,June,Eggs,Food,30.0,,2022,Wednesday

In [13]:
df.columns = df.columns.str.strip()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3510 entries, 0 to 3509
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             3510 non-null   datetime64[ns]
 1   Month            3510 non-null   object
 2   Name of expense  3510 non-null   object
 3   Type of expense  3510 non-null   object
 4   Amount           3510 non-null   float64
 5   Comments         3510 non-null   object
 6   Year             3510 non-null   int64
 7   Day              3510 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 219.5+ KB

**Data Analysis**

In [15]:
df['Year'].value_counts()

Year
2023    1577
2024    1511
2022     315
2025     107
Name: count, dtype: int64

In [18]:
df['Type of expense'].value_counts()

Type of expense
Transport            738
Food                 668
Thrills              363
Entertainment        300
Goodwill             207
Withdrawals          192
Credit               191
Accessories          122
Utilities            120
Withdrawal costs     106
Petty Cash            82
Savings               70
Disparity             50
Clothes               46
Shopping              44
Medicine              40
Vacation              40
Household Items       37
Debt                  33
Self Improvement      21
Birthday Expenses     16
Withdrawal Costs      12
Electronics            5
Home Shopping          4
Stationery             2
DIsparity              1
Name: count, dtype: int64

In [19]:
disparity_row = df[df['Name of expense'] == 'DIsparity']
disparity_row

,Date,Month,Name of expense,Type of expense,Amount,Comments,Year,Day
1422,2023-09-30,September,DIsparity,DIsparity,11.0,,2023,Saturday

In [20]:
df['Day'].value_counts()

Day
Friday       652
Saturday     566
Thursday     533
Wednesday    506
Tuesday      426
Monday       422
Sunday       405
Name: count, dtype: int64

In [21]:
df['Name of expense'].value_counts()

Name of expense
Fare                    558
Credit                  195
Uber                    170
Goodwill                157
Breakfast               117
                       ...
KDF                       1
Roro's date with Cee      1
Mouse                     1
Shillingi Fund            1
Karura Entrance Fees      1
Name: count, Length: 782, dtype: int64

In [23]:
from loguru import logger
logger.info("Data Cleaning Completed")

2025-02-19 01:09:15.887 | INFO     | __main__:<module>:2 - Data Cleaning Completed